open Common
(* Provides the 'Arg', 'Cmd', 'Manpage', and 'Term' modules. *)
open Cmdliner

(*****************************************************************************)
(* Prelude *)
(*****************************************************************************)

(*****************************************************************************)
(* Types and constants *)
(*****************************************************************************)

type conf = {
  targets: Fpath.t list;
  action: action_kind option;
}
and action_kind = 
  | DumpAST
  | DumpCFG
[@@deriving show]

let _default: conf = {
    targets = [];
    action = None;
}

type exit_code = int

(*************************************************************************)
(* Command-line flags *)
(*************************************************************************)

(* ------------------------------------------------------------------ *)
(* Positional arguments *)
(* ------------------------------------------------------------------ *)

let o_targets : string list Term.t =
  let info =
    Arg.info [] ~docv:"TARGETS" ~doc:{|Files to be analyzed by otip.|}
  in
  Arg.value (Arg.pos_all Arg.string ([]) info)

(* ------------------------------------------------------------------ *)
(* Alternate modes (actions) *)
(* ------------------------------------------------------------------ *)

let o_dump_ast : bool Term.t =
  let info =
    Arg.info [ "dump-ast" ] ~doc:{|Dump the AST of the target.|}
  in
  Arg.value (Arg.flag info)

let o_dump_cfg : bool Term.t =
  let info =
    Arg.info [ "dump-cfg" ] ~doc:{|Dump the CFG of the target.|}
  in
  Arg.value (Arg.flag info)

(*****************************************************************************)
(* Turn argv into a conf *)
(*****************************************************************************)

let cmdline_term : conf Term.t =
  (* !The parameters must be in alphabetic orders to match the order
   * of the corresponding '$ o_xx $' further below! *)
  let combine _dump_ast _dump_cfg targets =
    let targets = targets |> Common.map Fpath.v in
    (* TODO *)
    let action = None in
    { targets; 
      action;
    }
  in
  (* Term defines 'const' but also the '$' operator *)
  Term.(
    (* !the o_xxx must be in alphabetic orders to match the parameters of
     * combine above! *)
    const combine $ o_dump_ast $ o_dump_cfg $ o_targets
  )

let doc = "run analysis on TIP files"

let man : Manpage.block list =
  [
    `S Manpage.s_description;
    `P
      "Run analysis on TIP files.";
    `P "To get started quickly, run";
    `Pre "otip --dump-ast foo.tip";
    `P "For more information about TIP, see https://cs.au.dk/~amoeller/spa/";
  ]

let cmdline_info : Cmd.info = Cmd.info "otip" ~doc ~man

(*****************************************************************************)
(* Helpers *)
(*****************************************************************************)

(* Small wrapper around Cmdliner.Cmd.eval_value. *)
let eval_value ~argv cmd =
  (* the ~catch:false is to let non-cmdliner exn to bubble up *)
  match Cmd.eval_value ~catch:false ~argv cmd with
  (* 124 is the magic number chosen by Cmdliner for those errors, see
   * otip --help 'EXIT STATUS' section, which is autogenerated by Cmdliner
   *)
  | Error (`Term | `Parse) -> raise (UnixExit 124)
  (* this should never happen, because of the ~catch:false above *)
  | Error `Exn -> assert false
  | Ok ok -> (
      match ok with
      | `Ok config -> config
      | `Version
      | `Help ->
          raise (UnixExit 0))

(*****************************************************************************)
(* Entry point *)
(*****************************************************************************)

let parse_argv (argv : string array) : conf =
  let cmd : conf Cmd.t = Cmd.v cmdline_info cmdline_term in
  eval_value ~argv cmd

let run (_conf : conf) : exit_code =
  (* TODO *)
  0

let main (argv: string array) : exit_code =
  let conf = parse_argv argv in
  run conf
